version: "3"

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
        ports:
            - "8080:8080"
        command: sh -c "npm run serve"
        volumes:
            - ./frontend:/app
        depends_on: 
            - backend
            - postgres

    backend: &backend
        container_name: backend
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/code
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=postgres
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - postgres
    
    postgres:
        image: postgres:12-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
